// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	disbursementservice "github.com/hansengotama/disbursement/internal/service/disbursement"
	mock "github.com/stretchr/testify/mock"
)

// IDisbursementService is an autogenerated mock type for the IDisbursementService type
type IDisbursementService struct {
	mock.Mock
}

// RequestDisbursement provides a mock function with given fields: param
func (_m *IDisbursementService) RequestDisbursement(param disbursementservice.RequestDisbursementParam) error {
	ret := _m.Called(param)

	if len(ret) == 0 {
		panic("no return value specified for RequestDisbursement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(disbursementservice.RequestDisbursementParam) error); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDisbursementService creates a new instance of IDisbursementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDisbursementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDisbursementService {
	mock := &IDisbursementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
