CREATE TABLE wallets (
    user_id INT REFERENCES users(id) NOT NULL UNIQUE,
    balance DECIMAL CHECK (balance >= 0) NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ
);